sudo: required

language: python
python:
  - "3.4"
  - "3.5"

services:
  - docker
  - memcached

before_install:
  - cd build && ./build.sh surok_image
  - ./build.sh alpine
#  - ./build.sh centos
#  - ./build.sh centos_rpm
#  - ./build.sh fedora_rpm

# tests script
script:
  - ./runtests.sh
